#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:wonder}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:s3cr3t!}
