#Spring Data JPA
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:wonder_db}
spring.datasource.username=${POSTGRES_USER:wonder}
spring.datasource.password=${POSTGRES_PASSWORD:wonder}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.flyway.enabled=true

#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:wonder}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:s3cr3t!}